# Generated by Django 3.2.5 on 2021-07-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tode',
            new_name='Todo',
        ),
    ]
